{{- if and .Values.zabbixProxy.enable -}}
apiVersion: {{ template "zabbix.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: zabbix-proxy
  labels:
    app: zabbix
    tier: proxy
spec:
  selector:
    matchLabels:
      name: zabbix-proxy
  replicas: 1
  template:
    metadata:
      labels:
        name: zabbix-proxy
        app: zabbix
    spec:
      shareProcessNamespace: true
      containers:
        - name: zabbix-proxy
          image: "{{ .Values.zabbixProxy.image.repository }}:{{ .Values.zabbixProxy.image.tag }}"
          imagePullPolicy: {{ .Values.zabbixProxy.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.zabbixProxy.service.port }}
              protocol: TCP
              name: zabbix-proxy
          {{- with .Values.zabbixProxy.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.zabbixProxy.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.zabbixProxy.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.zabbixProxy.resources }}
          resources:
{{ toYaml .Values.zabbixProxy.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: storage-volume
              mountPath: "{{ .Values.zabbixProxy.persistentVolume.mountPath }}"
              subPath: "{{ .Values.zabbixProxy.persistentVolume.subPath }}"
          {{- if .Values.zabbixProxy.extraVolumeMounts }}
{{ toYaml .Values.zabbixProxy.extraVolumeMounts | indent 12 }}
          {{- end }}
          {{- if .Values.zabbixProxy.containerSecurityContext }}
          securityContext:
{{ toYaml .Values.zabbixProxy.containerSecurityContext | nindent 12 }}
          {{- end }}
          env:
            {{- range .Values.zabbixProxy.env }}
            {{- if eq .name "ZBX_SERVER_HOST" }}
            {{- if and $.Values.zabbix_server_mysql.enable $.Values.zabbix_server_mysql.haNodes.enable }}
            - name: {{ .name }}
              value: {{ printf "%s.%s.svc.cluster.local;%s.%s.svc.cluster.local" (include "zabbix-server-mysql.fullname" $) $.Release.Namespace (include "zabbix-server-mysql-standby.fullname" $) $.Release.Namespace | quote }}
            {{- else if and $.Values.zabbix_server_mysql.enable }}
            - name: {{ .name }}
              value: {{ printf "%s.%s.svc.cluster.local" (include "zabbix-server-mysql.fullname" $) $.Release.Namespace | quote }}
            {{- else if empty .value }}
            - name: {{ .name }}
              value: "0.0.0.0"
            {{- else }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
            {{- else }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
            {{- end }}
            {{- if .Values.zabbixJavaGateway.enabled }}
            - name: ZBX_JAVAGATEWAY_ENABLE
              value: "true"
            - name: ZBX_JAVAGATEWAY
              value: {{ template "zabbix.javaGateway.fullname" . }}
            - name: ZBX_JAVAGATEWAYPORT
              value: {{ .Values.zabbixJavaGateway.service.port | quote }}
            {{- $exists := false }}
            {{- range .Values.zabbixProxy.env }}
              {{- if eq .name "ZBX_STARTJAVAPOLLERS" }}
                {{- $exists = true }}
              {{- end }}
            {{- end }}
            {{- if not $exists }}
            - name: ZBX_STARTJAVAPOLLERS
              value: "5"
            {{- end }}
            {{- end }}
      {{- if .Values.zabbixProxy.image.pullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.zabbixProxy.image.pullSecrets | indent 6 }}
      {{- end }}
      {{- if .Values.zabbixProxy.tolerations }}
      tolerations:
{{ toYaml .Values.zabbixProxy.tolerations | indent 6 }}
      {{- end }}
      {{- if .Values.zabbixProxy.affinity }}
      affinity:
{{ toYaml .Values.zabbixProxy.affinity | indent 6 }}
      {{- end }}
      {{- if .Values.zabbixProxy.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.zabbixProxy.nodeSelector | indent 8 }}
      {{- end }}
      volumes:
        - name: storage-volume
        {{- if .Values.zabbixProxy.persistentVolume.enabled }}
          persistentVolumeClaim:
            claimName: {{ if .Values.zabbixProxy.persistentVolume.existingClaim }}{{ .Values.zabbixProxy.persistentVolume.existingClaim }}{{- else }}{{ template "zabbix.proxy.fullname" . }}{{- end }}
        {{- else }}
          emptyDir: {}
        {{- end }}
        {{- if .Values.zabbixProxy.extraVolumes }}
{{ toYaml .Values.zabbixProxy.extraVolumes | indent 8 }}
        {{- end }}
{{- end }}
